export const roleOptions = ['admin', 'mentor', 'emprendedor']
export const enrollmentStatusOptions = ['pendiente', 'aceptada', 'rechazada']
export const reviewStatusOptions = ['pendiente', 'aprobado', 'rechazado']

export const resources = [
  {
    key: 'profiles',
    title: 'Perfiles',
    basePath: '/profiles/',
    idField: 'id',
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    createFields: [
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'password', label: 'Password', type: 'password', required: true, default: '123456' },
      { name: 'full_name', label: 'Nombre completo' },
      { name: 'faculty', label: 'Facultad' },
      { name: 'skills', label: 'Habilidades', type: 'list' },
      { name: 'role', label: 'Rol', type: 'select', options: roleOptions, default: 'emprendedor' },
    ],
    updateFields: [
      { name: 'full_name', label: 'Nombre completo' },
      { name: 'faculty', label: 'Facultad' },
      { name: 'skills', label: 'Habilidades', type: 'list' },
      { name: 'role', label: 'Rol', type: 'select', options: roleOptions },
    ],
  },
  {
    key: 'phases',
    title: 'Fases',
    basePath: '/phases/',
    idField: 'id',
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    createFields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'order', label: 'Orden', type: 'number', required: true },
    ],
    updateFields: [
      { name: 'name', label: 'Nombre' },
      { name: 'order', label: 'Orden', type: 'number' },
    ],
  },
  {
    key: 'cohorts',
    title: 'Convocatorias',
    basePath: '/cohorts/',
    idField: 'id',
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    createFields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'start_date', label: 'Fecha inicio', type: 'date' },
      { name: 'end_date', label: 'Fecha fin', type: 'date' },
    ],
    updateFields: [
      { name: 'name', label: 'Nombre' },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'start_date', label: 'Fecha inicio', type: 'date' },
      { name: 'end_date', label: 'Fecha fin', type: 'date' },
    ],
  },
  {
    key: 'enrollments',
    title: 'Inscripciones',
    basePath: '/enrollments/',
    idField: 'id',
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    createFields: [{ name: 'cohort_id', label: 'ID convocatoria', required: true }],
    updateFields: [{ name: 'status', label: 'Estado', type: 'select', options: enrollmentStatusOptions }],
    customActions: [
      {
        key: 'status',
        label: 'Cambiar estado',
        method: 'PUT',
        path: (item) => `/enrollments/${item.id}/status`,
        fields: [{ name: 'status', label: 'Estado', type: 'select', options: ['aceptada', 'rechazada'], required: true }],
      },
    ],
  },
  {
    key: 'projects',
    title: 'Proyectos',
    basePath: '/projects/',
    idField: 'id',
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    createFields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'cohort_id', label: 'ID convocatoria' },
    ],
    updateFields: [
      { name: 'name', label: 'Nombre' },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'cohort_id', label: 'ID convocatoria' },
      { name: 'current_phase_id', label: 'ID fase actual', type: 'number' },
    ],
    customActions: [
      {
        key: 'members-list',
        label: 'Ver miembros',
        method: 'GET',
        path: (item) => `/projects/${item.id}/members`,
      },
      {
        key: 'members-add',
        label: 'Agregar miembro',
        method: 'POST',
        path: (item) => `/projects/${item.id}/members`,
        fields: [{ name: 'user_id', label: 'ID usuario', required: true }],
      },
      {
        key: 'members-remove',
        label: 'Remover miembro',
        method: 'DELETE',
        path: (item, form) => `/projects/${item.id}/members/${form.user_id}`,
        fields: [{ name: 'user_id', label: 'ID usuario', required: true }],
      },
      {
        key: 'mentors-list',
        label: 'Ver mentores',
        method: 'GET',
        path: (item) => `/projects/${item.id}/mentors`,
      },
      {
        key: 'mentors-add',
        label: 'Asignar mentor',
        method: 'POST',
        path: (item) => `/projects/${item.id}/mentors`,
        fields: [{ name: 'mentor_id', label: 'ID mentor', required: true }],
      },
      {
        key: 'mentors-remove',
        label: 'Desasignar mentor',
        method: 'DELETE',
        path: (item, form) => `/projects/${item.id}/mentors/${form.mentor_id}`,
        fields: [{ name: 'mentor_id', label: 'ID mentor', required: true }],
      },
      {
        key: 'deliverables-list',
        label: 'Ver entregables',
        method: 'GET',
        path: (item) => `/projects/${item.id}/deliverables`,
      },
      {
        key: 'deliverables-add',
        label: 'Subir entregable',
        method: 'POST',
        path: (item) => `/projects/${item.id}/deliverables`,
        fields: [
          { name: 'phase_id', label: 'ID fase', type: 'number', required: true },
          { name: 'file_url', label: 'URL archivo', required: true },
        ],
      },
    ],
  },
  {
    key: 'posts',
    title: 'Publicaciones',
    basePath: '/posts/',
    idField: 'id',
    canCreate: true,
    canUpdate: true,
    canDelete: true,
    createFields: [
      { name: 'title', label: 'Titulo', required: true },
      { name: 'content', label: 'Contenido', type: 'textarea', required: true },
      { name: 'image_url', label: 'URL imagen' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox', default: false },
    ],
    updateFields: [
      { name: 'title', label: 'Titulo' },
      { name: 'content', label: 'Contenido', type: 'textarea' },
      { name: 'image_url', label: 'URL imagen' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'deliverables',
    title: 'Entregables',
    basePath: '/deliverables/',
    idField: 'id',
    canList: false,
    canCreate: false,
    canUpdate: true,
    canDelete: true,
    updateFields: [
      { name: 'phase_id', label: 'ID fase', type: 'number' },
      { name: 'file_url', label: 'URL archivo' },
    ],
    customActions: [
      {
        key: 'reviews-list',
        label: 'Ver revisiones',
        method: 'GET',
        path: (item) => `/deliverables/${item.id}/reviews`,
      },
      {
        key: 'reviews-add',
        label: 'Crear revision',
        method: 'POST',
        path: (item) => `/deliverables/${item.id}/reviews`,
        fields: [
          { name: 'status', label: 'Estado', type: 'select', options: ['aprobado', 'rechazado'], required: true },
          { name: 'feedback', label: 'Feedback', type: 'textarea' },
        ],
      },
    ],
  },
  {
    key: 'reviews',
    title: 'Revisiones',
    basePath: '/reviews/',
    idField: 'id',
    canList: false,
    canCreate: false,
    canUpdate: true,
    canDelete: true,
    updateFields: [
      { name: 'status', label: 'Estado', type: 'select', options: reviewStatusOptions },
      { name: 'feedback', label: 'Feedback', type: 'textarea' },
    ],
  },
]
